[grid]
# hidden_dim = [128, 256, 512]
hidden_dim = [256]
# out_features = [128, 256, 512]
# num_transformer_heads = [2,4,8,16]
# dropout = [0.0, 0.1, 0.15, 0.2 ]
# scheduler_type = ["plateau","none"]
# lr = [1e-4, 1e-5]
# weight_decay = [0.0, 1e-5]

[defaults]
hidden_dim = 512
# mamba_d_state = 6
# mamba_layer_number = 4
# pers_loss_type = 'rmse_gl'
